# Generated by Django 5.2.2 on 2025-06-10 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_sensores_unidade_medida_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sensores',
            unique_together=set(),
        ),
    ]
