# Generated by Django 5.2.2 on 2025-06-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_historico_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='sensor',
            field=models.CharField(choices=[('contador', 'Contador'), ('luminosidade', 'Luminosidade'), ('temperatura', 'Temperatura'), ('umidade', 'Umidade')], max_length=100),
        ),
    ]
